version: "3"

services:
  api:
    image: seo-link-checker-api:1.0.0
    build: ./Backend
    container_name: api
    restart: always
    volumes:
      - ./Backend/:/app/api/
    ports:
      - "3201:3201"

  ui:
    image: seo-link-checker-ui:1.0.0
    build: ./Frontend
    container_name: ui
    restart: always
    ports:
      - "3200:8080"
